export const AG_GRID_LOCALE_AR = {
    selectAll: "(تحديد الكل)",
    selectAllSearchResults: "(تحديد جميع نتائج البحث)",
    addCurrentSelectionToFilter: "إضافة التحديد الحالي إلى الفلتر",
    searchOoo: "البحث...",
    blanks: "(فراغات)",
    noMatches: "لا توجد تطابقات",

    filterOoo: "تصفية...",
    equals: "متساوي",
    notEqual: "غير متساوي",
    blank: "فارغ",
    notBlank: "غير فارغ",
    empty: "اختر واحد",

    lessThan: "أقل من",
    greaterThan: "أكبر من",
    lessThanOrEqual: "أقل من أو يساوي",
    greaterThanOrEqual: "أكبر من أو يساوي",
    inRange: "بين",
    inRangeStart: "من",
    inRangeEnd: "إلى",

    contains: "يحتوي على",
    notContains: "لا يحتوي على",
    startsWith: "يبدأ بـ",
    endsWith: "ينتهي بـ",

    dateFormatOoo: "yyyy-mm-dd",
    before: "قبل",
    after: "بعد",

    andCondition: "و",
    orCondition: "أو",

    applyFilter: "تطبيق",
    resetFilter: "إعادة تعيين",
    clearFilter: "مسح",
    cancelFilter: "إلغاء",

    textFilter: "تصفية النص",
    numberFilter: "تصفية الرقم",
    dateFilter: "تصفية التاريخ",
    setFilter: "تعيين تصفية",

    groupFilterSelect: "حدد الحقل:",

    advancedFilterContains: "يحتوي",
    advancedFilterNotContains: "لا يحتوي",
    advancedFilterTextEquals: "يساوي",
    advancedFilterTextNotEqual: "لا يساوي",
    advancedFilterStartsWith: "يبدأ بـ",
    advancedFilterEndsWith: "ينتهي بـ",
    advancedFilterBlank: "فارغ",
    advancedFilterNotBlank: "غير فارغ",
    advancedFilterEquals: "=",
    advancedFilterNotEqual: "!=",
    advancedFilterGreaterThan: "أكبر من",
    advancedFilterGreaterThanOrEqual: "أكبر من أو يساوي",
    advancedFilterLessThan: "أقل من",
    advancedFilterLessThanOrEqual: "أقل من أو يساوي",
    advancedFilterTrue: "صحيح",
    advancedFilterFalse: "غير صحيح",
    advancedFilterAnd: "و",
    advancedFilterOr: "أو",
    advancedFilterApply: "تطبيق",
    advancedFilterBuilder: "بنّاء",
    advancedFilterValidationMissingColumn: "العمود مفقود",
    advancedFilterValidationMissingOption: "الخيار مفقود",
    advancedFilterValidationMissingValue: "القيمة مفقودة",
    advancedFilterValidationInvalidColumn: "العمود غير موجود",
    advancedFilterValidationInvalidOption: "الخيار غير موجود",
    advancedFilterValidationMissingQuote: "القيمة تفتقر إلى علامة اقتباس نهائية",
    advancedFilterValidationNotANumber: "القيمة ليست رقمًا",
    advancedFilterValidationInvalidDate: "القيمة ليست تاريخًا صالحًا",
    advancedFilterValidationMissingCondition: "الشرط مفقود",
    advancedFilterValidationJoinOperatorMismatch:
        "مشغلات الانضمام داخل الشرط يجب أن تكون متطابقة",
    advancedFilterValidationInvalidJoinOperator: "مشغل الانضمام غير موجود",
    advancedFilterValidationMissingEndBracket: "ناقص القوس النهائي",
    advancedFilterValidationExtraEndBracket: "يوجد أكثر من القوس النهائي",
    advancedFilterValidationMessage: "التعبير به خطأ. ${variable} - ${variable}.",
    advancedFilterValidationMessageAtEnd: "التعبير به خطأ. ${variable} في نهاية التعبير.",
    advancedFilterBuilderTitle: "تصفية متقدمة",
    advancedFilterBuilderApply: "تطبيق",
    advancedFilterBuilderCancel: "إلغاء",
    advancedFilterBuilderAddButtonTooltip: "إضافة تصفية أو مجموعة",
    advancedFilterBuilderRemoveButtonTooltip: "إزالة",
    advancedFilterBuilderMoveUpButtonTooltip: "الانتقال لأعلى",
    advancedFilterBuilderMoveDownButtonTooltip: "الانتقال لأسفل",
    advancedFilterBuilderAddJoin: "إضافة مجموعة",
    advancedFilterBuilderAddCondition: "إضافة تصفية",
    advancedFilterBuilderSelectColumn: "تحديد عمود",
    advancedFilterBuilderSelectOption: "تحديد خيار",
    advancedFilterBuilderEnterValue: "أدخل قيمة...",
    advancedFilterBuilderValidationAlreadyApplied: "التصفية الحالية تم تطبيقها بالفعل.",
    advancedFilterBuilderValidationIncomplete: "لم يتم استكمال جميع الشروط.",
    advancedFilterBuilderValidationSelectColumn: "يجب تحديد عمود.",
    advancedFilterBuilderValidationSelectOption: "يجب تحديد خيار.",
    advancedFilterBuilderValidationEnterValue: "يجب إدخال قيمة.",

    columns: "الأعمدة",
    filters: "الفلاتر",
    pivotMode: "وضع البيفوت",
    groups: "مجموعات الصفوف",
    rowGroupColumnsEmptyMessage: "اسحب هنا لتحديد مجموعات الصفوف",
    values: "القيم",
    valueColumnsEmptyMessage: "اسحب هنا للتجميع",
    pivots: "تصنيف الأعمدة",
    pivotColumnsEmptyMessage: "اسحب هنا لتحديد تصنيف الأعمدة",

    group: "مجموعة",

    rowDragRow: "صف",
    rowDragRows: "صفوف",

    loadingOoo: "جار التحميل...",
    loadingError: "خطأ",
    noRowsToShow: "لا توجد صفوف لعرضها",
    enabled: "مُفعل",

    pinColumn: "تثبيت العمود",
    pinLeft: "تثبيت لليسار",
    pinRight: "تثبيت لليمين",
    noPin: "لا تثبيت",
    valueAggregation: "تجميع القيم",
    noAggregation: "بلا",
    autosizeThiscolumn: "تحجيم تلقائي لهذا العمود",
    autosizeAllColumns: "تحجيم تلقائي لكل الأعمدة",
    groupBy: "تجميع حسب",
    ungroupBy: "إلغاء التجميع حسب",
    ungroupAll: "إلغاء تجميع الكل",
    addToValues: "إضافة ${variable} إلى القيم",
    removeFromValues: "إزالة ${variable} من القيم",
    addToLabels: "إضافة ${variable} إلى التصنيفات",
    removeFromLabels: "إزالة ${variable} من التصنيفات",
    resetColumns: "إعادة تعيين الأعمدة",
    expandAll: "توسيع جميع مجموعات الصفوف",
    collapseAll: "طي جميع مجموعات الصفوف",
    copy: "نسخ",
    ctrlC: "Ctrl+C",
    ctrlX: "Ctrl+X",
    copyWithHeaders: "نسخ مع الرؤوس",
    copyWithGroupHeaders: "نسخ مع رؤوس المجموعات",
    cut: "قص",
    paste: "لصق",
    ctrlV: "Ctrl+V",
    export: "تصدير",
    csvExport: "تصدير إلى CSV",
    excelExport: "تصدير إلى Excel",
    columnFilter: "تصفية العمود",
    columnChooser: "اختيار الأعمدة",
    sortAscending: "ترتيب تصاعدي",
    sortDescending: "ترتيب تنازلي",
    sortUnSort: "إلغاء الترتيب",

    ariaColumnPanelList: "قائمة الأعمدة",
    ariaFilterPanelList: "قائمة الفلاتر",

    thousandSeparator: "٬",
    decimalSeparator: ".",

    true: "صحيح",
    false: "خطأ",
    invalidDate: "تاريخ غير صالح",
    invalidNumber: "رقم غير صالح",
    january: "يناير",
    february: "فبراير",
    march: "مارس",
    april: "أبريل",
    may: "مايو",
    june: "يونيو",
    july: "يوليو",
    august: "أغسطس",
    september: "سبتمبر",
    october: "أكتوبر",
    november: "نوفمبر",
    december: "ديسمبر",

    timeFormatSlashesDDMMYYYY: "DD/MM/YYYY",
    timeFormatSlashesMMDDYYYY: "MM/DD/YYYY",
    timeFormatSlashesDDMMYY: "DD/MM/YY",
    timeFormatSlashesMMDDYY: "MM/DD/YY",
    timeFormatDotsDDMYY: "DD.M.YY",
    timeFormatDotsMDDYY: "M.DD.YY",
    timeFormatDashesYYYYMMDD: "YYYY-MM-DD",
    timeFormatSpacesDDMMMMYYYY: "DD MMMM YYYY",
    timeFormatHHMMSS: "HH:MM:SS",
    timeFormatHHMMSSAmPm: "HH:MM:SS AM/PM",
};
